# Generated by Django 3.1.7 on 2021-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
